name: aoc

data-files:
    - data/*/*.*

dependencies:
  - array
  - attoparsec
  - base == 4.*
  - bytestring
  - containers
  - mtl
  - split
  - text
  - vector

library:
  source-dirs: src

executables:
  aoc-executable:
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    - base == 4.*
    - hspec
    - QuickCheck
    verbatim: |
      build-tool-depends:
          hspec-discover:hspec-discover
