name: aoc

data-files:
    - data/*/*.*

dependencies:
  - array
  - attoparsec
  - base == 4.*
  - bytestring
  - containers
  - mtl
  - split
  - text
  - vector

library:
  source-dirs: src

executables:
  aoc-executable:
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
