name: aoc

data-files:
    - data/*.*

dependencies:
  - base == 4.*

library:
  source-dirs: src

executables:
  aoc-executable:
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
